### ISSUE TITLE
Two file-scope constants named Rows and Columns make the Cataclysm module fragile to unity block boundaries

### ISSUE THREAD

**Issue by sdubois777** [sdubois777/Cataclysm#1469]
> **Correction, same day.** This issue first said that adding a new test file
> stopped the `Cataclysm` module compiling. **That causal claim was not
> established and is probably wrong.** `development` did not compile at
> `82f9276` on a clean tree, which is
> [#1462](https://github.com/sdubois777/Cataclysm/issues/1462), filed
> independently with its own build log. My build log shows only that both
> colliding files were inside unity blocks; because pulling my own modified
> files out of the unity set also repacks the blocks, my evidence cannot tell
> the two stories apart. What is below is rewritten to claim only what is
> established.

`game/Source/Cataclysm/Interface/CataclysmInventoryScreen.cpp` declares two
constants in an anonymous namespace, named `Rows` and `Columns`. Unreal compiles
a module as a **unity build**: several `.cpp` files are concatenated into one
translation unit. An anonymous namespace is file scope to the compiler and
**module scope inside that unit**, so those two names are visible to every other
file that lands in the same block, and a parameter of the same name shadows
them. The build treats warnings as errors:

```
CataclysmDropRoll.cpp(1442,44): error C4459: declaration of 'Rows' hides global declaration
	auto HasUntaken = [](const TArray<FName>& Rows, const TSet<FName>& Taken)
CataclysmInventoryScreen.cpp(23,18): note: see declaration of '`anonymous-namespace'::Rows'
	constexpr int32 Rows = UCataclysmInventoryComponent::Rows;
```

## Why it is not one bad line

`Rows` is an ordinary parameter name in this module:

| File | Declarations taking a parameter named `Rows` |
| :-- | --: |
| `game/Source/Cataclysm/Character/CataclysmEnemyModifiers.cpp` | 9 |
| `game/Source/Cataclysm/Interface/CataclysmCreaturePanel.cpp` | 1 |
| `game/Source/Cataclysm/Items/CataclysmDropRoll.cpp` | 1 |

Any of those landing in the same block as `CataclysmInventoryScreen.cpp` produces
the same error. **Which files share a block depends on how many files the module
has and what order they are in**, so adding, removing or renaming an unrelated
file moves the boundaries and can expose a different pair.

## Why nobody sees it while they are working

The build log says it: `Using 'git status' to determine working set for adaptive
non-unity build`. **A file you have modified is compiled on its own**, where
nothing else declares the same names. A session editing either file builds green
every time; the collision appears only once the tree is clean and the files are
merged. Continuous integration does not compile C++ at all — that is #20 — so
nothing else catches it.

## What is already fixed

Two sessions hit this independently on 2026-09-07 and fixed it from opposite
ends of the same collision:

| Branch | What it renames |
| :-- | :-- |
| `fix/unity-build-name-collision` (#1462) | the lambda parameter in `CataclysmDropRoll.cpp`, `Rows` to `BandRows` |
| `feat/empire-run-difficulty-tier` (#1444) | the constants in `CataclysmInventoryScreen.cpp`, `Rows` and `Columns` to `GridRows` and `GridColumns` |

They touch different files and do not conflict. The second removes the shadowed
names entirely, so no parameter named `Rows` or `Columns` anywhere in the module
can collide with them; the first removes one of the eleven candidates. Which one
survives is being settled between those two branches.

## What is not fixed, and is this issue

**Nothing stops the next one.** A short, common name in an anonymous namespace in
any file of this module is a build failure waiting for the block boundaries to
move. It lands confusingly: it names two files, neither of which the author
changed, and it does not reproduce if the blocks happen to shift back.

A guard would be a Python test in `tools/tests/`, in the shape the guards there
already take. Two possible forms, in increasing strictness:

1. Collect every name declared at namespace scope inside an anonymous namespace
   in `game/Source/*/*.cpp`, collect every parameter name in the same module, and
   fail on an intersection. This is what actually breaks the build.
2. Simpler and blunter: fail on an anonymous-namespace name that is short and
   generic, against a small list — `Rows`, `Columns`, `Index`, `Count`, `Total`,
   `Name`, `Path`, `Map`. Cheaper to write, and it would have caught this one.

Whoever builds it should confirm it fails on the original names before believing
it, per `CLAUDE.md`: put `Rows` back in `CataclysmInventoryScreen.cpp` and check
the guard names that file.

**This is a different concern from forcing a clean-tree build before merge**,
which #1462 raises and which is about when a build is trusted rather than about
what names are safe.

## What this is not

It is not a compiler setting to change. Turning C4459 off would hide a real
hazard: the constant and the parameter genuinely have the same name in one
translation unit, and which one a line refers to depends on where it is.

**Comment by sdubois777** [comment]
Closed by the backlog session on the master session's instruction. Already fixed on origin/development at b5683e16 (landed in #1474, merge commit 4fc1e9d0). `game/Source/Cataclysm/Interface/CataclysmInventoryScreen.cpp` lines 49 and 52 now read `constexpr int32 GridColumns = UCataclysmInventoryComponent::Columns;` and `constexpr int32 GridRows = UCataclysmInventoryComponent::Rows;`; the file-scope names Rows and Columns are gone from that file.
