### ISSUE TITLE
development does not compile: a lambda parameter and an anonymous-namespace constant both named Rows collide under the unity build

### ISSUE THREAD

**Issue by sdubois777** [sdubois777/Cataclysm#1468]
## What is wrong

**`development` does not compile.** `python tools/unreal_build.py build` fails on
`82f9276`, the current head, with warnings-as-errors:

```
game\Source\Cataclysm\Items\CataclysmDropRoll.cpp(1442,44): error C4459:
declaration of 'Rows' hides global declaration
        constexpr int32 Rows = UCataclysmInventoryComponent::Rows;
                        ^
Result: Failed (OtherCompilationError)
```

Measured 2026-09-07 in a clean worktree branched from `82f9276` with no C++
changes of its own. `tools/unreal_build.py build` exits 1, which is correct.

## Why neither file is wrong on its own

**The two names are in different translation units, and the unity build puts
them in one.** Both of these are included into
`game/Intermediate/Build/Win64/x64/UnrealEditor/Development/Cataclysm/Module.Cataclysm.6.cpp`,
at its lines 22 and 29:

| File | Line | What it declares |
| :-- | --: | :-- |
| `game/Source/Cataclysm/Interface/CataclysmInventoryScreen.cpp` | 23 | `constexpr int32 Rows = UCataclysmInventoryComponent::Rows;`, inside an anonymous namespace |
| `game/Source/Cataclysm/Items/CataclysmDropRoll.cpp` | 1442 | a lambda parameter `const TArray<FName>& Rows` |

Compiled separately neither shadows anything. Compiled together the lambda
parameter hides the file-scope constant and C4459 fires. An anonymous namespace
does not help: it makes the name internal to the translation unit, and under a
unity build the translation unit is the whole blob.

`Columns` on the line above it has the same shape and has not collided yet.

## Why nothing caught it

Continuous integration runs `python -m pytest` and `python -m ruff check .` and
nothing else. `CLAUDE.md` says so. **No automated check compiles the C++ on a
pull request**, so a build break merges silently and is found by the next person
who tries to build.

The lambda was added by the enchantment drawback work,
[#1453](https://github.com/sdubois777/Cataclysm/issues/1453) /
[#1457](https://github.com/sdubois777/Cataclysm/pull/1457) — the comment above it
reads "ASKED WITHOUT DRAWING. DrawEnchantmentInBand would answer this too, but it
takes a number off the stream to do it".

## What it blocks

**Anything that needs the editor.** In particular
`python tools/run_editor_python.py tools/generate_datatable_assets.py`, which is
what turns `game/Data/*.csv` into the DataTable assets a packaged build loads.
`game/README.md` says the way to run that from a worktree is to build the editor
target there first, and that build is this one. So a change to any generated CSV
cannot have its asset rebuilt from a worktree until this compiles.

It is blocking [#950](https://github.com/sdubois777/Cataclysm/issues/950) now:
`game/Data/PassiveNodes.csv` and `game/Data/PassiveEdges.csv` gained the Ravager
and Ritualist trees, and `tools/tests/test_datatable_assets_are_current.py` fails
until their assets are rebuilt.

## What to do

Rename one of the two. The lambda parameter is the cheaper one to change and the
more local — it is used three lines below it and nowhere else — so
`CandidateRows` or `Pool` in `CataclysmDropRoll.cpp` fixes it without touching
the inventory screen.

**Then consider whether the real fault is that nothing compiles the C++ on a pull
request.** That is a separate concern and should be its own issue if it is
wanted; #20 already covers the self-hosted runner the Unreal job would need.

**Comment by sdubois777** [comment]
Duplicate of #1462, which was opened first and is the better record of the two.

Both describe the same fault: a lambda parameter named `Rows` in `game/Source/Cataclysm/Items/CataclysmDropRoll.cpp` line 1442 collides with an anonymous-namespace constant of the same name in `game/Source/Cataclysm/Interface/CataclysmInventoryScreen.cpp` line 23, once Unreal's unity build compiles both into one translation unit.

**#1462 has the part this issue was missing**, and it is the part worth keeping: it explains why the session that wrote the original code saw a green build. The build log says `Using 'git status' to determine working set for adaptive non-unity build` — a modified file is compiled on its own, where nothing else declares `Rows`, so the collision only appears once the file is committed and the tree is clean. That is a general trap rather than a fact about this one file.

The fix is on `fix/unity-build-name-collision` (b3ff826), not from here. My own branch for it, #1473, is closed as a duplicate.
