### ISSUE TITLE
development does not compile: a lambda parameter shadows a constant once the unity build merges the files

### ISSUE THREAD

**Issue by sdubois777** [sdubois777/Cataclysm#1462]
**`development` at 82f9276 does not compile.** The C++ never reaches continuous integration, so nothing caught it and it was merged.

## The error

```
CataclysmDropRoll.cpp(1442,44): error C4459: declaration of 'Rows' hides global declaration
	auto HasUntaken = [](const TArray<FName>& Rows, const TSet<FName>& Taken)

CataclysmInventoryScreen.cpp(23,18): note: see declaration of 'anonymous-namespace::Rows'
	constexpr int32 Rows = UCataclysmInventoryComponent::Rows;
```

Result: Failed (OtherCompilationError), after 23.76 seconds.

## Why every check passed

**Two independent reasons, and both need fixing separately from this.**

**The C++ is never compiled by continuous integration.** The only job that runs is the Python fast suite. Unreal continuous integration is issue #20 and needs a self-hosted runner registered, so a change that does not compile can pass every check a pull request has.

**The unity build hides it while the file is uncommitted.** The build log says it plainly: `Using 'git status' to determine working set for adaptive non-unity build`. A modified file is compiled on its own, where nothing else declares `Rows`. Once committed and the tree clean, it is merged into `Module.Cataclysm.6.cpp` alongside `CataclysmInventoryScreen.cpp`, and the collision appears.

So the session that wrote it built successfully, ran the full Unreal automation suite at 1450 passed, and was right that its own evidence was sound — **its tree was dirty every time it built.**

## The fix

Rename the lambda parameter. No behaviour change.

## What this does not fix, and what should be opened separately

**Nothing forces a clean-tree build before merge.** The rule exists in CLAUDE.md — build again with the tree clean before believing a green build — and it is guidance a session has to remember, with nothing checking it. Every C++ change merged since the last clean-tree build is unverified in the same way.

**Comment by sdubois777** [comment]
Fixed in #1473, squashed onto development as 087d879. Verified by content: CandidateRows appears twice in game/Source/Cataclysm/Items/CataclysmDropRoll.cpp on origin/development, where the colliding name was before.

Verified as compiling, which is the part that matters for this particular fault and which no automated check performs. The fix commit was checked out detached in the main checkout, confirmed to have the rename on disk, confirmed to have no modified C++ so the file would actually be grouped into a shared compilation unit, and built: Build: Succeeded, exit 0.

The merged tree is byte for byte the tree that was compiled:

    merged tree    817fd57443bc683857c24d4f68e3f78b90b8ae4e
    compiled tree  817fd57443bc683857c24d4f68e3f78b90b8ae4e

That check exists because a session pointed out that a squash merge produces a different commit and could in principle change how the compilation blocks are packed. It cannot here: the pull request carried one commit whose parent was exactly the previous head, so the tree carried over unchanged and the module's file set is identical.

Two independent measurements confirmed the failure was already on development rather than being caused by any branch. The build log here is one. The other is from the difficulty tier session: the two colliding files sit in the same compilation block, Module.Cataclysm.6.cpp, both with and without that session's new test file present, so no added file brought them together.

A count in this issue's discussion was wrong and is corrected here. I reported eleven declarations that could shadow the constant. It is fourteen, out of fifteen matching lines. My search was piped through a line limit and I counted the truncated output, which reads as a complete list. There is also one declaration that could shadow Columns, in CataclysmInventoryScreenTests.cpp, which no rename in the drop-roll file affects.

What this does NOT fix stays open. Nothing forces a clean-tree build before a merge, and continuous integration never compiles C++ at all, so the next collision reaches development the same way. Four have now. #1469 proposes a Python guard against short common names in anonymous namespaces in this module, and #20 is the missing self-hosted runner that would let continuous integration build the game.
